Home/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
    url(r'^$', views.Index, name="Index"),
    url(r'^register/', views.Register, name="Register"),
    url(r'^tollregister/', views.TollRegister, name="TollRegister"),
    url(r'^login/', views.LoggingIn, name="Login"),
    url(r'^allauthRegistration/', views.allauthRegistration, name='allauthRegistration'),
    url(r'^Forget/', views.ForgetPassword, name='forget'),
    url(r'^NewPass/', views.NewPass, name='NewPass'),
    url(r'^ForgetPass/',views.NewPassword, name='forgetpassword'),
]

TollBooth/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from Home import views
from TollBooth import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('accounts/', include('allauth.urls')),
    path('admindash/', include('AdminDashboard.urls')),
    path('Workers/', include('WorkersDashboard.urls')),
    path('Customers/', include('CustomerDashboard.urls')),
    path('logout/', views.Logout, name="logout"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

WorkersDashboard/urls.py
from django.urls import path
from . import views

app_name = "WorkersDashboard"
urlpatterns = [
    path('Dashboard/', views.index, name="workersIndex"),

    path('WokrersList/', views.WorkersLists, name="workersWorkersList"),

    path('ListRoute/', views.ListRoutes, name="workersListRoute"),

    path('ListTollBooth/', views.ListTollBooths, name="workersListTollBooth"),

    path('ListAmount/', views.ListAmounts, name="workersListAmount"),

    path('ListBooking/', views.BookingHistory, name="workersListBooking"),

    path('EditProfile/', views.EditProfile, name="workersEditProfile"),
    path('UpdateProfile/', views.UpdateProfile, name="workersUpdateProfile"),
    path('UpdatePassword/', views.UpdatePassword, name="workersChangePassword"),
    path('DeleteAccount/', views.DeleteAccount, name="workersDeleteAccount"),

    path('CheckStatus/', views.CheckStatus, name="CheckStatus"),
    path('SaveImage/', views.SaveImage, name="SaveImage"),

]

WorkersDashboard/models.py
from django.db import models

# Create your models here.

WorkersDashboard/views.py
import base64
import datetime
import json
import io
import os
from google.cloud import vision_v1p3beta1 as vision
import cv2
import pandas as pd
from PIL import Image
from django.core.files.base import ContentFile
from django.views.decorators.csrf import csrf_exempt
from CustomerDashboard.models import *
from django.contrib import messages
from django.contrib.auth.hashers import make_password
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render
from AdminDashboard.models import *
from Home.models import *
from TollBooth import settings

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = os.path.join(settings.CHECK_IMG, 'JSON FILE NAME')
SOURCE_PATH = settings.CHECK_IMG


# Create your views here.


def index(request):
    id = request.session['userid']
    datime = datetime.date.today()
    route = Registration.objects.get(loginid=id, loginid__isdeleted=False, loginid__roleid=2)
    routeid = TollRegisterAdditional.objects.get(workerid=route.id)
    routename = routeid.Tollid.TollName
    routenam = routename.replace('TBooth', "")
    noofworkersrt = TollRegisterAdditional.objects.filter(workerid__loginid__roleid=2,
                                                          workerid__loginid__isdeleted=False,
                                                          Tollid__TollName=routename).count()
    noofworkers = Login.objects.filter(roleid=2, isdeleted=False, isapproved=True, status=True).count()
    noofbooths = AddToll.objects.filter(isdeleted=False).count()
    tollob = TollRegisterAdditional.objects.get(workerid__loginid=id)
    field_object = TollRegisterAdditional._meta.get_field('Tollid')
    field_value = field_object.value_from_object(tollob)
    noofbooking = Booking.objects.filter(isCanceled=False, TollID=field_value, isExpired=False).count()
    context = {
        'datetime': datime,
        'noofworkers': noofworkers,
        'noofbooths': noofbooths,
        'routename': routenam,
        'noofworkersrt': noofworkersrt,
        'noofbooking': noofbooking
    }
    return render(request, "WorkersDashboard/workersIndex.html", context)


def WorkersLists(request):
    workerid = request.session["tollid"]
    tollobj = TollRegisterAdditional.objects.get(workerid=workerid)
    field_object = TollRegisterAdditional._meta.get_field('Tollid')
    field_value = field_object.value_from_object(tollobj)
    log = TollRegisterAdditional.objects.select_related().filter(Tollid=field_value, workerid__loginid__isapproved=True,
                                                                 workerid__loginid__status=True,
                                                                 workerid__loginid__isdeleted=False,
                                                                 workerid__loginid__roleid=2)
    return render(request, "WorkersDashboard/workersWorkersList.html", {'log': log})


def ListRoutes(request):
    location = AddLocations.objects.filter(isdeleted=False)
    routeob = AddRoute.objects.select_related().filter(isdeleted=False)
    return render(request, "WorkersDashboard/workersListRoute.html", {'routeobj': routeob, 'location': location})


def ListTollBooths(request):
    routes = AddRoute.objects.filter(isdeleted=False)
    tolls = AddToll.objects.select_related().filter(isdeleted=False)
    return render(request, "WorkersDashboard/workersListTollBooth.html", {'routes': routes, 'tolls': tolls})


def ListAmounts(request):
    workerid = request.session["tollid"]
    tollobj = TollRegisterAdditional.objects.get(workerid=workerid)
    field_object = TollRegisterAdditional._meta.get_field('Tollid')
    field_value = field_object.value_from_object(tollobj)
    stoll = AddToll.objects.filter(isdeleted=False)
    vtype = AddVehicle.objects.filter(isdeleted=False)
    charge = AddPriceCharge.objects.select_related().filter(isdeleted=False, TollID=field_value)
    return render(request, "WorkersDashboard/workersAmount.html", {'vtype': vtype, 'charge': charge, 'stoll': stoll})


def EditProfile(request):
    toll = AddToll.objects.filter(isdeleted=False)
    return render(request, "WorkersDashboard/workersProfile.html", {'tolls': toll})


def UpdateProfile(request):
    toll = AddToll.objects.filter(isdeleted=False)
    if request.method == "POST":
        username = request.POST.get('username')
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        address = request.POST.get('address')
        email = request.POST.get('email')
        phone = request.POST.get('mobile')

        id = request.session['userid']
        logobj = Login.objects.get(pk=id)
        logobj.username = username
        logobj.save()
        regobj = Registration.objects.get(loginid=id)
        regobj.FirstName = firstname
        regobj.LastName = lastname
        regobj.Address = address
        regobj.Email = email
        regobj.Phone = phone
        if phone.isdigit() and len(phone) == 10 or len(phone) == 12:
            regobj.save()
            messages.success(request, "Updated Successfully")
            return HttpResponseRedirect('/Workers/EditProfile')
        else:
            toll = AddToll.objects.filter(isdeleted=False)
            return render(request, "WorkersDashboard/workersProfile.html", {'tolls': toll, 'number': 'Invalid Number'})
    return render(request, "WorkersDashboard/workersProfile.html", {'tolls': toll})


def UpdatePassword(request):
    id = request.session['userid']
    if request.method == "POST":
        password = request.POST.get('newpassword')
        logobj = Login.objects.get(pk=id)
        logobj.password = make_password(password, salt=None, hasher='default')
        logobj.save()
        messages.success(request, "Password Changed Successfully")
        return HttpResponseRedirect('/Workers/EditProfile')
    return render(request, "WorkersDashboard/workersProfile.html")


def DeleteAccount(request):
    id = request.session['userid']
    logobj = Login.objects.get(pk=id)
    logobj.isdeleted = True
    logobj.save()
    return HttpResponseRedirect('/logout')


def BookingHistory(request):
    return render(request, "WorkersDashboard/workersBooking.html")


def CheckStatus(request):
    loginid = request.session['userid']
    dates = datetime.datetime.now().date()
    tollob = TollRegisterAdditional.objects.get(workerid__loginid=loginid)
    bookob = Booking.objects.filter(TollID=tollob.Tollid, isCanceled=False, isExpired=False,
                                    DateBooked=dates).order_by('-pk') | Booking.objects.filter(TollID=tollob.Tollid, isCanceled=False,
                                                                               isExpired=False, DateExpired=dates).order_by('-pk')
    context = {
        'booking': bookob
    }
    return render(request, "WorkersDashboard/workersCheck.html", context)


@csrf_exempt
def SaveImage(request):
    getfinalnumber = ""
    loginid = request.session['userid']
    if request.method == "POST":
        dir = settings.CHECK_IMG
        counter = 1
        payload = json.loads(request.body)
        image_data = payload['imageData']
        format, imgstr = image_data.split(';base64,')
        data = ContentFile(base64.b64decode(imgstr))
        imageobj = Image.open(data)
        rotatatedimg = imageobj.transpose(Image.FLIP_LEFT_RIGHT)
        finaldir = ""
        myfile = ""
        while counter > 0:
            myfile = "image-" + str(counter) + ".png"
            finaldir = os.path.join(dir, myfile)
            if os.path.isfile(finaldir):
                counter += 1
            else:
                break
        imageobj.save(finaldir)
        getfinalnumber = SearchNumber(myfile, loginid)
        data = {'msg': str(getfinalnumber)}
        return JsonResponse(data)


def SearchNumber(myfile, loginid):
    finalnumber = ""
    img_path = os.path.join(settings.CHECK_IMG, myfile)
    dates = datetime.datetime.now().date()
    tollob = TollRegisterAdditional.objects.get(workerid__loginid=loginid)
    bookobs = Booking.objects.filter(TollID=tollob.Tollid, isCanceled=False, isExpired=False,
                                     DateBooked=dates) | Booking.objects.filter(TollID=tollob.Tollid, isCanceled=False,
                                                                                isExpired=False, DateExpired=dates)
    trial = []
    for i in bookobs:
        getst = str(i.VehicleID.VehicleRegNum)
        trial.append(getst)
    number = []
    for i in bookobs:
        getstring = str(i.VehicleID.VehicleRegNum).replace('-', "")
        number.append(getstring)

    img = cv2.imread(img_path)
    height, width = img.shape[:2]
    img = cv2.resize(img, (800, int((height * 800) / width)))
    imgs = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    imgb = cv2.bilateralFilter(imgs, 11, 17, 17)

    outputpath = os.path.join(settings.OUTPUTPATH, 'outputimage.png')
    cv2.imwrite(outputpath, imgb)
    img_path = outputpath

    client = vision.ImageAnnotatorClient()

    with io.open(img_path, 'rb') as image_file:
        content = image_file.read()
    image = vision.types.Image(content=content)

    response = client.text_detection(image=image)
    texts = response.text_annotations
    df = pd.DataFrame(columns=['description'])
    for obj in texts:
        df = df.append(
            dict(
                description=obj.description,
            ),
            ignore_index=True
        )
    print(df)
    if df.empty:
        finalnumber = "The Number is not found!"
        return finalnumber
    temp = []
    val = ""
    for i in df.description:
        val = val + i
        temp.append(val)
    inpu = [''.join(x) for x in zip(*[iter(temp[-1])] * 1)]

    new = []
    for i in number:
        news = [''.join(x) for x in zip(*[iter(i)] * 1)]
        new.append(news)

    count = 0
    for k in new:
        count += 1

    checkvalue = [[] for _ in range(count)]
    for j in range(count):
       for i in new[j]:

templates/WorkersDashboard/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/WorkersDashboard/workersBase.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Welcome | {{ logindetails.username }}</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'workers/images/favicon.png' %}">
    <!-- Pignose Calender -->
    <link href="{% static 'workers/plugins/pg-calendar/css/pignose.calendar.min.css' %}" rel="stylesheet">
    <!-- Chartist -->
    <link rel="stylesheet" href="{% static 'workers/plugins/chartist/css/chartist.min.css' %}">
    <link rel="stylesheet" href="{% static 'workers/plugins/chartist-plugin-tooltips/css/chartist-plugin-tooltip.css' %}">
    <link href="{% static 'workers/plugins/tables/css/datatable/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/9e9d15e133.js" crossorigin="anonymous"></script>
    <!-- Custom Stylesheet -->
    <link href="{% static 'workers/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'workers/icons/fontawesome-free-5.12.1-web/css/all.min.css' %}" rel="stylesheet">

</head>

<body>

    <!--*******************
        Preloader start
    ********************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header">
            <div class="brand-logo">
                <a href="{% url 'WorkersDashboard:workersIndex' %}">
                    <b class="logo-abbr"><span style="font-size: 25px; color: white; font-weight: bold">TB</span> </b>
                    <span class="logo-compact" style="font-weight: bold; color: white; font-size: 30px;">TBOOTH</span>
                    <span class="brand-title" style="font-weight: bold; color: white; font-size: 30px;">
                        TBOOTH
                    </span>
                </a>
            </div>
        </div>
        <!--**********************************
            Nav header end
        ***********************************-->

        <!--**********************************
            Header start
        ***********************************-->

        <div class="header">
            <div class="header-content clearfix">

                <div class="nav-control">
                    <div class="hamburger">
                        <span class="toggle-icon"><i class="icon-menu"></i></span>
                    </div>

                </div>
                <div class="header-left">
                    <div class="input-group icons">
                        <h2 style="color:rgba(14,13,12,0.93)">Welcome, {{ logindetails.username }}</h2>
                    </div>
                </div>
                <div class="header-right">
                    <ul class="clearfix">
                        <li class="icons dropdown">
                            <div class="user-img c-pointer position-relative"   data-toggle="dropdown">
                                <span class="activity active"></span>
                                <img src="{{ userdetails.Image.url }}" height="40" width="40" alt="">
                            </div>
                            <div class="drop-down dropdown-profile animated fadeIn dropdown-menu">
                                <div class="dropdown-content-body">
                                    <ul>
                                        <li>
                                            <a href="{% url 'WorkersDashboard:workersEditProfile' %}"><i class="fas fa-user-secret"></i> <span>Profile</span></a>
                                        </li>

                                        <hr class="my-2">
                                        <li><a href="{% url 'logout' %}"><i class="fas fa-power-off"></i> <span>Logout</span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            {% include 'WorkersDashboard/messages.html' %}
        </div>
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->

        <!--**********************************
            Sidebar start
        ***********************************-->
        <div class="nk-sidebar">
            <div class="nk-nav-scroll">
                <ul class="metismenu" id="menu">
                    <li class="nav-label">Dashboard</li>
                    <li>
                        <a href="{% url 'WorkersDashboard:workersIndex' %}" aria-expanded="false">
                            <i class="fab fa-dashcube menu-icon"></i><span class="nav-text">Dashboard</span>
                        </a>
                    </li>
                    <li class="mega-menu mega-menu-sm">
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="fas fa-users menu-icon"></i><span class="nav-text">Registered Users</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'WorkersDashboard:workersWorkersList' %}">Workers</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="{% url 'WorkersDashboard:workersListRoute' %}" aria-expanded="false">
                            <i class="fas fa-road menu-icon"></i><span class="nav-text">List Route</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'WorkersDashboard:workersListTollBooth' %}" aria-expanded="false">
                            <i class="fas fa-torii-gate menu-icon"></i><span class="nav-text">List TollBooth</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'WorkersDashboard:workersListAmount' %}" aria-expanded="false">
                            <i class="fas fa-rupee-sign menu-icon"></i><span class="nav-text">Amount</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'WorkersDashboard:workersListBooking' %}" aria-expanded="false">
                            <i class="fas fa-history menu-icon"></i><span class="nav-text">Booking History</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'WorkersDashboard:CheckStatus' %}" aria-expanded="false">
                            <i class="fas fa-search menu-icon"></i><span class="nav-text">Check</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        {% block body_block %}


        {% endblock %}
        <div class="footer">
            <div class="copyright">
                <p>Copyright &copy; Designed & Developed by dN</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->
    </div>
    <!--*******************
        Preloader end
    ********************-->


    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->

    <!--**********************************
        Scripts
    ***********************************-->
    <script src="{% static 'workers/plugins/common/common.min.js' %}"></script>
    <script src="{% static 'workers/js/custom.min.js' %}"></script>
    <script src="{% static 'workers/js/settings.js' %}"></script>
    <script src="{% static 'workers/js/gleek.js' %}"></script>
    <script src="{% static 'workers/js/styleSwitcher.js' %}"></script>

    <!-- Chartjs -->
    <script src="{% static 'workers/plugins/chart.js/Chart.bundle.min.js' %}"></script>
    <!-- Circle progress -->
    <script src="{% static 'workers/plugins/circle-progress/circle-progress.min.js' %}"></script>
    <!-- Datamap -->
    <script src="{% static 'workers/plugins/d3v3/index.js' %}"></script>
    <script src="{% static 'workers/plugins/topojson/topojson.min.js' %}"></script>
    <script src="{% static 'workers/plugins/datamaps/datamaps.world.min.js' %}"></script>
    <!-- Morrisjs -->
    <script src="{% static 'workers/plugins/raphael/raphael.min.js' %}"></script>
    <script src="{% static 'workers/plugins/morris/morris.min.js' %}"></script>
    <!-- Pignose Calender -->
    <script src="{% static 'workers/plugins/moment/moment.min.js' %}"></script>
    <script src="{% static 'workers/plugins/pg-calendar/js/pignose.calendar.min.js' %}"></script>
    <!-- ChartistJS -->
    <script src="{% static 'workers/plugins/chartist/js/chartist.min.js' %}"></script>
    <script src="{% static 'workers/plugins/chartist-plugin-tooltips/js/chartist-plugin-tooltip.min.js' %}"></script>
    <script src="{% static 'workers/plugins/tables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'workers/plugins/tables/js/datatable/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'workers/plugins/tables/js/datatable-init/datatable-basic.min.js' %}"></script>


    <script src="{% static 'workers/js/dashboard/dashboard-1.js' %}"></script>

    <script>
        setTimeout(function () {
        if($("#msg").length > 0) {
            $("#msg").remove();
        }
        }, 4000)
    </script>
</body>
</html>

templates/WorkersDashboard/workersIndex.html
{% extends 'WorkersDashboard/workersBase.html' %}
{% block body_block %}
{% load static %}
            <div class="content-body">

            <div class="container-fluid mt-3">
                <div class="row">
                    <div class="col-lg-3 col-sm-6">
                        <div class="card gradient-1">
                            <div class="card-body">
                                <h3 class="card-title text-white">Registered Workers</h3>
                                <div class="d-inline-block">
                                    <h2 class="text-white">{{ noofworkers }}</h2>
                                    <p class="text-white mb-0">Updated: {{ datetime | date:"M d" }}</p>
                                </div>
                                <span class="float-right display-5 opacity-5"><i class="fas fa-users-cog"></i></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6" onclick="window.location.href='{% url 'WorkersDashboard:workersWorkersList' %}'">
                        <div class="card gradient-2">
                            <div class="card-body">
                                <h3 class="card-title text-white">Workers in {{ routename }}</h3>
                                <div class="d-inline-block">
                                    <h2 class="text-white">{{ noofworkersrt }}</h2>
                                    <p class="text-white mb-0">Updated: {{ datetime | date:"M d" }}</p>
                                </div>
                                <span class="float-right display-5 opacity-5"><i class="fa fa-users"></i></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6" onclick="window.location.href='{% url 'WorkersDashboard:workersListTollBooth' %}'">
                        <div class="card gradient-3">
                            <div class="card-body">
                                <h3 class="card-title text-white">Registered TollBooths</h3>
                                <div class="d-inline-block">
                                    <h2 class="text-white">{{ noofbooths }}</h2>
                                    <p class="text-white mb-0">Updated: {{ datetime | date:"M d" }}</p>
                                </div>
                                <span class="float-right display-5 opacity-5"><i class="fas fa-registered"></i></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6" onclick="window.location.href='{% url 'WorkersDashboard:workersListBooking' %}'">
                        <div class="card gradient-4">
                            <div class="card-body">
                                <h3 class="card-title text-white">Booking</h3>
                                <div class="d-inline-block">
                                    <h2 class="text-white">{{ noofbooking }}</h2>
                                    <p class="text-white mb-0">Updated: {{ datetime | date:"M d" }}</p>
                                </div>
                                <span class="float-right display-5 opacity-5"><i class="fa fa-bookmark"></i></span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Booking History</h4>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead >
                                            <tr>
                                                <th>#</th>
                                                <th>First Name</th>
                                                <th>Mobile</th>
                                                <th>Email</th>
                                                <th>Register No</th>
                                                <th>TollBooth</th>
                                                <th>Amount</th>
                                                <th>Booked On</th>
                                                <th>Expired On</th>
                                                <th>Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for i in bookobj %}
                                            <tr>
                                            <td>{{ forloop.counter }}</td>
                                            {% for j in newuserobj %}
                                            {% if i.loginid == j.loginid %}
                                            <td>{{ j.FirstName }}</td>
                                            <td>{{j.Phone }}</td>
                                            <td>{{ j.Email }}</td>
                                            {% endif %}
                                            {% endfor %}
                                            <td>{{ i.VehicleID.VehicleRegNum }}</td>
                                            <td>{{ i.TollID.TollName }}</td>
                                            <td>{{ i.AmountID.Amount }}</td>
                                            <td>{{ i.DateBooked }} {{ i.TimeBooked }}</td>
                                            <td>{{ i.DateExpired }} {{ i.TimeExpired }}</td>
                                                {% if i.isExpired == True and i.isCanceled == False and i.VehicleID.isdeleted == False %}
                                                    <td class="text-danger" style="font-weight: bold;">Expired</td>
                                                {% elif i.isExpired == False and i.isCanceled == False and i.VehicleID.isdeleted == False %}
                                                    <td class="text-info" style="font-weight: bold;">Active</td>
                                                {% elif i.isCanceled == True and i.isExpired == True and i.VehicleID.isdeleted == False %}
                                                    <td class="text-danger" style="font-weight: bold;">Canceled</td>
                                                {% endif %}
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <!-- #/ container -->
        </div>
{% endblock %}