CustomerDashboard/urls.py
from django.urls import path
from . import views

app_name = "CustomerDashboard"
urlpatterns = [
    path('Dashboard/', views.CustomerIndex, name="CustomerIndex"),

    path('ListVehicleReg/', views.ListVehicleReg, name="ListVehicleReg"),
    path('AddVehicleReg/', views.AddVehicleReg, name="AddVehicleReg"),
    path('EditVehicleReg/<int:pk>', views.EditVehicleReg, name="EditVehicleReg"),
    path('UpdateVehicleReg/', views.UpdateVehicleReg, name="UpdateVehicleReg"),
    path('DeleteVehicleReg/<int:pk>', views.DeleteVehicleReg, name="DeleteVehicleReg"),

    path('Booking/', views.BookNow, name="Booking"),
    path('Checkout/', views.Checkout, name="Checkout"),
    path('EditBooking/<int:pk>', views.EditBooking, name="EditBooking"),
    path('UpdateBooking/', views.UpdateBooking, name="UpdateBooking"),
    path('CancelBooking/', views.CancelBooking, name="CancelBooking"),
    path('ListBooking/', views.ListBooking, name="ListBooking"),

    path('GetRegValue/<int:pk>', views.GetRegValue, name="GetRegValue"),
    path('GetTollValue/<str:pk>', views.GetTollValue, name="GetTollValue"),
    path('GetExpiry/<str:pk>', views.GetExpiry, name="GetExpiry"),

    path('UpdateProfile/', views.UpdateProfile, name="CustomerUpdateProfile"),
    path('UpdatePassword/', views.UpdatePassword, name="CustomerChangePassword"),
    path('DeleteAccount/', views.DeleteAccount, name="CustomerDeleteAccount"),
]

Home/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
    url(r'^$', views.Index, name="Index"),
    url(r'^register/', views.Register, name="Register"),
    url(r'^tollregister/', views.TollRegister, name="TollRegister"),
    url(r'^login/', views.LoggingIn, name="Login"),
    url(r'^allauthRegistration/', views.allauthRegistration, name='allauthRegistration'),
    url(r'^Forget/', views.ForgetPassword, name='forget'),
    url(r'^NewPass/', views.NewPass, name='NewPass'),
    url(r'^ForgetPass/',views.NewPassword, name='forgetpassword'),
]

TollBooth/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from Home import views
from TollBooth import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('accounts/', include('allauth.urls')),
    path('admindash/', include('AdminDashboard.urls')),
    path('Workers/', include('WorkersDashboard.urls')),
    path('Customers/', include('CustomerDashboard.urls')),
    path('logout/', views.Logout, name="logout"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

CustomerDashboard/models.py
from django.db import models
from AdminDashboard.models import *
from Home.models import Login


# Create your models here.
class VehicleReg(models.Model):
    loginid = models.ForeignKey(Login, on_delete=models.CASCADE)
    VehicleTypeID = models.ForeignKey(AddVehicle, on_delete=models.CASCADE)
    VehicleRegNum = models.CharField(max_length=15)
    isdeleted = models.BooleanField(default=False)


class Booking(models.Model):
    loginid = models.ForeignKey(Login, on_delete=models.CASCADE)
    TollID = models.ForeignKey(AddToll, on_delete=models.CASCADE)
    DateBooked = models.DateField(auto_now_add=False)
    TimeBooked = models.TimeField(auto_now_add=False, default="00:00:00")
    TimeExpired = models.TimeField(auto_now_add=False, default="00:00:00")
    DateExpired = models.DateField(auto_now_add=False)
    VehicleID = models.ForeignKey(VehicleReg, on_delete=models.CASCADE)
    AmountID = models.ForeignKey(AddPriceCharge, on_delete=models.CASCADE)
    isExpired = models.BooleanField(default=False)
    isCanceled = models.BooleanField(default=False)

CustomerDashboard/views.py
from builtins import getattr
from datetime import timedelta
import datetime
import json
from django.contrib import messages
from django.contrib.auth.hashers import make_password
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template, render_to_string
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render
from .models import *
from Home.models import *
from AdminDashboard.models import *
# Create your views here.


def CustomerIndex(request):
    logid = request.session['userid']
    datime = datetime.date.today()
    noofbooths = AddToll.objects.filter(isdeleted=False).count()
    noofveh = VehicleReg.objects.filter(isdeleted=False, loginid=request.session['userid']).count()
    bookobj = Booking.objects.filter(loginid=logid, isCanceled=False, VehicleID__isdeleted=False).order_by('-id')
    noofbooking = Booking.objects.filter(loginid=logid, isExpired=False, isCanceled=False).count()
    context = {
        'datetime': datime,
        'noofbooths': noofbooths,
        'noofveh': noofveh,
        'bookobj': bookobj,
        'noofbooking': noofbooking,
    }
    return render(request, "CustomerDashboard/customerIndex.html", context)


def AddVehicleReg(request):
    id = request.session['userid']
    category = AddVehicle.objects.filter(isdeleted=False)
    if request.method == "POST":
        vtype = request.POST.get('category')
        regno = request.POST.get('regnum')

        vreg = VehicleReg()
        lobj = Login.objects.get(pk=id)
        print(lobj)
        vobj = AddVehicle.objects.get(VehicleType=vtype, isdeleted=False)
        vreg.loginid = lobj
        vreg.VehicleTypeID = vobj
        vreg.VehicleRegNum = regno
        vreg.isdeleted = False
        if VehicleReg.objects.filter(VehicleRegNum=regno).filter(isdeleted=False).exists():
            messages.warning(request, "Already Exist!")
            return HttpResponseRedirect('/Customers/ListVehicleReg')
        else:
            vreg.save()
            messages.success(request, "Added Successfully")
            return HttpResponseRedirect('/Customers/ListVehicleReg')
    return render(request, "CustomerDashboard/customerListVehicle.html", {'category': category})


def EditVehicleReg(request, pk):
    vob = VehicleReg.objects.get(pk=pk)
    data = {
        'Id': vob.pk,
        'VehicleType': vob.VehicleTypeID.VehicleType,
        'VehicleReg': vob.VehicleRegNum
    }
    return JsonResponse(data)


def UpdateVehicleReg(request):
    if request.POST.get('action') == 'post':
        id = request.POST.get('id')
        vtype = request.POST.get('VehicleType')
        vreg = request.POST.get('VehicleReg')
        vobj = AddVehicle.objects.get(VehicleType=vtype, isdeleted=False)
        vehobj = VehicleReg.objects.get(pk=id)
        vehobj.VehicleTypeID = vobj
        vehobj.VehicleRegNum = vreg
        if VehicleReg.objects.filter(VehicleRegNum=vreg).filter(isdeleted=False).exists():
            message = {'error': "Already exists"}
            messages.warning(request, "Already Exist!")
            return JsonResponse(message)
        else:
            vehobj.save()
            message = {'message': 'Success'}
            messages.success(request, "Updated Successfully")
            return JsonResponse(message)


def DeleteVehicleReg(request, pk):
    vob = VehicleReg.objects.get(pk=pk)
    vob.isdeleted = True
    if Booking.objects.filter(VehicleID=pk, isCanceled=False).exists():
        bob = Booking.objects.get(VehicleID=pk, isCanceled=False)
        bob.isCanceled = True
        bob.isExpired = True
        bob.save()
    vob.save()
    messages.error(request, "Deleted Successfully")
    return HttpResponseRedirect('/Customers/ListVehicleReg')


def ListVehicleReg(request):
    id = request.session['userid']
    details = Registration.objects.get(loginid=id)
    vehdetails = VehicleReg.objects.filter(isdeleted=False, loginid=id)
    category = AddVehicle.objects.filter(isdeleted=False).order_by('-VehicleType')
    context = {
        'vehdetails': vehdetails,
        'category': category,
        'details': details,
    }
    return render(request, "CustomerDashboard/customerListVehicle.html", context)


def BookNow(request):
    id = request.session['userid']
    details = Registration.objects.get(loginid=id)
    regdetails = VehicleReg.objects.filter(loginid=id, isdeleted=False)
    vehdetails = AddVehicle.objects.filter(isdeleted=False)
    location = AddToll.objects.filter(isdeleted=False)
    toll = AddToll.objects.filter(isdeleted=False)
    context = {
        'details': details,
        'vehdetails': vehdetails,
        'regdetails': regdetails,
        'location': location,
        'toll': toll,
    }
    if request.method == "POST":
        logid = request.session['userid']
        vreg = request.POST.get('meid')
        vtype = request.POST.get('mevtid')
        tollid = request.POST.get('mtid')
        dtbook = request.POST.get('datebooked')
        dtexpired = request.POST.get('menowexdate')
        log = Login.objects.get(pk=logid)
        tempmail = Registration.objects.get(loginid=logid)
        toll = AddToll.objects.get(pk=tollid)
        vregistration = VehicleReg.objects.get(pk=vreg)
        tempamnt = AddPriceCharge.objects.filter(TollID=tollid, VehicleTypeID=vtype).values_list('pk', flat=True)
        amountobj = AddPriceCharge.objects.get(pk=tempamnt[0])

        bookobj = Booking()
        try:
            orderpk = Booking.objects.latest('pk')
            orderid = int(orderpk.pk) + 1
        except:
            orderid = 1
        bookobj.loginid = log
        bookobj.TollID = toll
        bookobj.DateBooked = dtbook
        bookobj.TimeBooked = datetime.datetime.now().time()
        bookobj.TimeExpired = datetime.datetime.now().time()
        bookobj.DateExpired = dtexpired
        bookobj.VehicleID = vregistration
        bookobj.AmountID = amountobj
        if Booking.objects.filter(VehicleID=vreg, TollID=tollid, DateBooked=dtbook, isExpired=False,
                                  isCanceled=False).exists():
            messages.warning(request, "Already Exist!")
            return HttpResponseRedirect('/Customers/Booking')
        else:
            return render(request, "CustomerDashboard/Checkout.html", {'content': bookobj, 'temp': tempmail, 'orderid': orderid})
    return render(request, "CustomerDashboard/customerBooking.html", context)


def Checkout(request):
    loginid = request.POST.get('loginid')
    tollid = request.POST.get('tollid')
    datebooked = request.POST.get('datebooked')
    dateexpired = request.POST.get('dateexpired')
    vehicleid = request.POST.get('vehicleid')
    amountid = request.POST.get('amountid')

    log = Login.objects.get(pk=loginid)
    toll = AddToll.objects.get(pk=tollid)
    vregistration = VehicleReg.objects.get(pk=vehicleid)
    amountobj = AddPriceCharge.objects.get(pk=amountid)
    email = Registration.objects.get(loginid=loginid)

    bookobj = Booking()
    bookobj.loginid = log
    bookobj.TollID = toll
    bookobj.DateBooked = datebooked
    bookobj.TimeBooked = datetime.datetime.now().time()
    bookobj.TimeExpired = datetime.datetime.now().time()
    bookobj.DateExpired = dateexpired
    bookobj.VehicleID = vregistration
    bookobj.AmountID = amountobj
    bookobj.isExpired = False
    bookobj.isCanceled = False
    bookobj.save()
    context = {
        'bookobj': bookobj
    }
    subject, from_email, to = 'Order Details of BookingID# {}'.format(bookobj.pk), 'YOUR MAIL ID', str(email.Email)
    text_content = 'Hi,' + bookobj.loginid.username + ', \nYour order for BookingID# '+ str(bookobj.pk) +' was succesfully booked on '+ str(bookobj.DateBooked) +' for the TollBooth '+ bookobj.TollID.TollName+ '.\nRegard dN'
    html_content = render_to_string('CustomerDashboard/bookingmail.html', context)
    mail = EmailMultiAlternatives(subject, text_content, from_email, [to])
    mail.attach_alternative(html_content, "text/html")
    mail.send()
    messages.success(request, "Hello {0}, Your BookingID# {1} has booked succesfully ".format(log.username, bookobj.pk))
    return HttpResponseRedirect('/Customers/ListBooking')


def EditBooking(request, pk):
    lob = Booking.objects.get(pk=pk)
    vehid_object = Booking._meta.get_field('VehicleID')
    vehid = vehid_object.value_from_object(lob)

    vtypeob = VehicleReg.objects.get(pk=vehid)
    vtype_object = VehicleReg._meta.get_field('VehicleTypeID')
    vtypeid = vtype_object.value_from_object(vtypeob)

    tollid_object = Booking._meta.get_field('TollID')
    tollid = tollid_object.value_from_object(lob)

    routeob = AddToll.objects.get(pk=tollid)
    route_object = AddToll._meta.get_field('RouteID')
    routeid = route_object.value_from_object(routeob)

    data = {
        'ID': lob.pk,
        'rno': lob.VehicleID.VehicleRegNum,
        'rnoid': vehid,
        'vtype': lob.VehicleID.VehicleTypeID.VehicleType,
        'vtypeid': vtypeid,
        'tbooth': lob.TollID.TollName,
        'tboothid': tollid,
        'routeid': routeid,
        'sloc': lob.TollID.RouteID.SourceLoc.CityName,
        'dloc': lob.TollID.RouteID.DestinationLoc.CityName,
        'amount': lob.AmountID.Amount,
        'datebooked': lob.DateBooked,
        'dateexpired': lob.DateExpired,
    }
    return JsonResponse(data)


def UpdateBooking(request):
    if request.method == "POST":
        id = request.POST.get('mebookid')
        vreg = request.POST.get('meid')
        vtype = request.POST.get('mevtid')
        tollid = request.POST.get('mtid')
        dtbook = request.POST.get('datebooked')
        dtexpired = request.POST.get('menowexdate')

        toll = AddToll.objects.get(pk=tollid)
        vregistration = VehicleReg.objects.get(pk=vreg)
        tempamnt = AddPriceCharge.objects.filter(TollID=tollid, VehicleTypeID=vtype).values_list('pk', flat=True)
        amountobj = AddPriceCharge.objects.get(pk=tempamnt[0])

templates/CustomerDashboard/Checkout.html
{% extends "CustomerDashboard/customerBase.html" %}
{% block body_block %}
{% load static %}

    <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'CustomerDashboard:CustomerIndex' %}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'CustomerDashboard:Booking' %}">Booking</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Checkout</a></li>
                    </ol>
                </div>
            </div>

            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6 card" style="padding:50px;">
                                        <h4><strong>Details for OrderID# {{ orderid }}</strong></h4><br>
                                        {{ temp.FirstName }}<br>
                                        {{ temp.Phone }}<br>
                                        {{ temp.Email }}<br>
                                        <hr>
                                        OrderID# {{ orderid }}<br><br>
                                        {{ content.VehicleID.VehicleRegNum }}<br>
                                        {{ content.TollID.TollName }}<br>
                                        {{ content.TollID.RouteID.SourceLoc.CityName }} - {{ content.TollID.RouteID.DestinationLoc.CityName }}<br>
                                        {{ content.DateBooked}} {{ content.TimeBooked }}<br>
                                        {{ content.DateExpired }} {{ content.TimeExpired }}<br>
                                        <br>
                                        <br>
                                        <h4><span style="color: rgba(246,82,73,0.93);font-weight: bold">Total Amount:</span> Rs. {{ content.AmountID.Amount }}</h4>
                                    </div>
                                    <div class="col-md-6 card" style="padding:50px;">
                                        <h4 class="text-center"><strong>You can pay using:</strong></h4>
                                        <br><br>
                                        <div class="text-center">
                                            <img src="{% static 'customer/icons/credit-card.svg' %}" class="rounded" style="height: 45%; width:45%;">
                                        </div>
                                        <br><br>
                                        <div id="paypal-button-container"></div>
                                        <script src="https://www.paypal.com/sdk/js?client-id=CLIENT ID_&currency=INR"></script>

                                        <script>
                                            paypal.Buttons({

                                                style: {
                                                    color:  'gold',
                                                    size: 'responsive',
                                                    },

                                                // Set up the transaction
                                                createOrder: function(data, actions) {
                                                    return actions.order.create({
                                                        purchase_units: [{
                                                            amount: {
                                                                value: '{{ content.AmountID.Amount }}'
                                                            }
                                                        }]
                                                    });
                                                },

                                                // Finalize the transaction
                                                onApprove: function(data, actions) {
                                                    return actions.order.capture().then(function(details) {
                                                        // Show a success message to the buyer
                                                        {#alert('Transaction completed by {{ temp.FirstName }} !');#}
                                                        $("#payment").modal({
                                                            backdrop: 'static',
                                                            keyboard: false,
                                                        })

                                                    });
                                                }


                                            }).render('#paypal-button-container');
                                        </script>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>

     <div class="modal fade bd-example-modal-sm" id="payment" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content" style="border: none">
                <div class="modal-header" style="background-color: #CBE558;">
                    <h5 class="modal-title" style="color: rgba(6,6,6,0.93);"><strong>Payment Status</strong></h5>

                </div>
                <div class="modal-body">
                <form method="post" id="formpaymentsubmit" name="formpaymentsubmit" action="{% url 'CustomerDashboard:Checkout' %}">
                    {% csrf_token %}
                    <h4 class="text-center">Your payment is successfull</h4>
                    <div class="text-center">
                        <small>BookingID# {{ orderid }}</small>
                    </div>
                    <br>
                    <div class="text-center">
                        <img src="{% static 'customer/icons/tick.svg' %}" style="width: 100px; height:100px">
                    </div>
                    <input type="hidden" name="loginid" id="loginid" value="{{ content.loginid.pk }}">
                    <input type="hidden" name="tollid" id="tollid" value="{{ content.TollID.pk }}">
                    <input type="hidden" name="datebooked" id="datebooked" value="{{ content.DateBooked }}">
                    <input type="hidden" name="dateexpired" id="dateexpired" value="{{ content.DateExpired }}">
                    <input type="hidden" name="vehicleid" id="vehicleid" value="{{ content.VehicleID.pk }}">
                    <input type="hidden" name="amountid" id="amountid" value="{{ content.AmountID.pk }}">
                        <br>
                        <br>
                    <div class="modal-footer">
                        <button type="submit" class="btn" style="color: rgba(6,6,6,0.93); background-color: #CBE558;"><strong><span class="fas fa-check" style="padding-right: 10px;"></span>Okay</strong></button>
                    </div>
                 </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/CustomerDashboard/customerBase.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Welcome | {{ logindetails.username }}</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'customer/images/favicon.png' %}">
    <!-- Pignose Calender -->
    <link href="{% static 'customer/plugins/pg-calendar/css/pignose.calendar.min.css' %}" rel="stylesheet">
    <!-- Chartist -->
    <link rel="stylesheet" href="{% static 'customer/plugins/chartist/css/chartist.min.css' %}">
    <link rel="stylesheet" href="{% static 'customer/plugins/chartist-plugin-tooltips/css/chartist-plugin-tooltip.css' %}">
    <link href="{% static 'customer/plugins/tables/css/datatable/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/9e9d15e133.js" crossorigin="anonymous"></script>
    <!-- Custom Stylesheet -->
    <link href="{% static 'customer/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'customer/icons/fontawesome-free-5.12.1-web/css/all.min.css' %}" rel="stylesheet">

</head>

<body>

    <!--*******************
        Preloader start
    ********************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header">
            <div class="brand-logo">
                <a href="{% url 'CustomerDashboard:CustomerIndex' %}">
                    <b class="logo-abbr"><span style="font-size: 25px; color: white; font-weight: bold">TB</span> </b>
                    <span class="logo-compact" style="font-weight: bold; color: white; font-size: 30px;">TBOOTH</span>
                    <span class="brand-title" style="font-weight: bold; color: white; font-size: 30px;">
                        TBOOTH
                    </span>
                </a>
            </div>
        </div>
        <!--**********************************
            Nav header end
        ***********************************-->

        <!--**********************************
            Header start
        ***********************************-->

        <div class="header">
            <div class="header-content clearfix">

                <div class="nav-control">
                    <div class="hamburger">
                        <span class="toggle-icon"><i class="icon-menu"></i></span>
                    </div>

                </div>
                <div class="header-left">
                    <div class="input-group icons">
                        <h2 style="color:rgba(14,13,12,0.93)">Welcome, {{ logindetails.username }}</h2>
                    </div>
                </div>
                <div class="header-right">
                    <ul class="clearfix">
                        <li class="icons dropdown">
                            <div class="user-img c-pointer position-relative"   data-toggle="dropdown">
                                <span class="activity active"></span>
                                <img src="{{ userdetails.Image.url }}" height="40" width="40" alt="">
                            </div>
                            <div class="drop-down dropdown-profile animated fadeIn dropdown-menu">
                                <div class="dropdown-content-body">
                                    <ul>
                                        <li>
                                            <a href="{% url 'CustomerDashboard:CustomerUpdateProfile' %}"><i class="fas fa-user-secret"></i> <span>Profile</span></a>
                                        </li>

                                        <hr class="my-2">
                                        <li><a href="{% url 'logout' %}"><i class="fas fa-power-off"></i> <span>Logout</span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            {% include 'CustomerDashboard/messages.html' %}
        </div>
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->

        <!--**********************************
            Sidebar start
        ***********************************-->
        <div class="nk-sidebar">
            <div class="nk-nav-scroll">
                <ul class="metismenu" id="menu">
                    <li class="nav-label">Dashboard</li>
                    <li>
                        <a href="{% url 'CustomerDashboard:CustomerIndex' %}" aria-expanded="false">
                            <i class="fab fa-dashcube menu-icon"></i><span class="nav-text">Dashboard</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'CustomerDashboard:ListVehicleReg' %}" aria-expanded="false">
                            <i class="fas fa-location-arrow menu-icon"></i><span class="nav-text">Add Vehicle Details</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'CustomerDashboard:Booking' %}" aria-expanded="false">
                            <i class="fas fa-torii-gate menu-icon"></i><span class="nav-text">Booking</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'CustomerDashboard:ListBooking' %}" aria-expanded="false">
                            <i class="fas fa-history menu-icon"></i><span class="nav-text">Booking History</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        {% block body_block %}


        {% endblock %}
        <div class="footer">
            <div class="copyright">
                <p>Copyright &copy; Designed & Developed by dN</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->
    </div>
    <!--*******************
        Preloader end
    ********************-->


    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->

    <!--**********************************
        Scripts
    ***********************************-->
    <script src="{% static 'customer/plugins/common/common.min.js' %}"></script>
    <script src="{% static 'customer/js/custom.min.js' %}"></script>
    <script src="{% static 'customer/js/settings.js' %}"></script>
    <script src="{% static 'customer/js/gleek.js' %}"></script>
    <script src="{% static 'customer/js/styleSwitcher.js' %}"></script>

    <!-- Chartjs -->
    <script src="{% static 'customer/plugins/chart.js/Chart.bundle.min.js' %}"></script>
    <!-- Circle progress -->
    <script src="{% static 'customer/plugins/circle-progress/circle-progress.min.js' %}"></script>
    <!-- Datamap -->
    <script src="{% static 'customer/plugins/d3v3/index.js' %}"></script>
    <script src="{% static 'customer/plugins/topojson/topojson.min.js' %}"></script>
    <script src="{% static 'customer/plugins/datamaps/datamaps.world.min.js' %}"></script>
    <!-- Morrisjs -->
    <script src="{% static 'customer/plugins/raphael/raphael.min.js' %}"></script>
    <script src="{% static 'customer/plugins/morris/morris.min.js' %}"></script>
    <!-- Pignose Calender -->
    <script src="{% static 'customer/plugins/moment/moment.min.js' %}"></script>
    <script src="{% static 'customer/plugins/pg-calendar/js/pignose.calendar.min.js' %}"></script>
    <!-- ChartistJS -->
    <script src="{% static 'customer/plugins/chartist/js/chartist.min.js' %}"></script>
    <script src="{% static 'customer/plugins/chartist-plugin-tooltips/js/chartist-plugin-tooltip.min.js' %}"></script>
    <script src="{% static 'customer/plugins/tables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'customer/plugins/tables/js/datatable/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'customer/plugins/tables/js/datatable-init/datatable-basic.min.js' %}"></script>


    <script src="{% static 'customer/js/dashboard/dashboard-1.js' %}"></script>

    <script>
        setTimeout(function () {
        if($("#msg").length > 0) {
            $("#msg").remove();
        }
        }, 4000)
    </script>
</body>
</html>

templates/CustomerDashboard/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}