AdminDashboard/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = "AdminDashboard"
urlpatterns = [
    path('admindashboard/', views.adminIndex, name="adminindex"),

    path('workerslist/', views.adminWorkersList, name="adminworkerslist"),
    path('ApproveWorkers/<int:id>', views.ApproveWorker, name="adminApproveWorker"),
    path('RejectWorkers/<int:id>', views.RejectWorker, name="adminRejectWorker"),

    path('customerslist/', views.adminCustomerList, name="admincustomerslist"),

    path('addDistrict/', views.AddDistricts, name="adminadddistrict"),
    path('addLocation/', views.AddLocation, name="adminaddlocation"),
    path('editLocation/<int:pk>', views.EditLocation, name="adminEditLocation"),
    path('updateLocation/', views.UpdateLocation, name="adminUpdateLocation"),
    path('deleteLocation/<int:pk>', views.DeleteLocation, name="adminDeleteLocation"),
    path('editDistrict/<int:pk>', views.EditDistrict, name="adminEditDistrict"),
    path('updateDistrict/', views.UpdateDistrict, name="adminUpdateDistrict"),
    path('deleteDistrict/<int:pk>', views.DeleteDistrict, name="adminDeleteDistrict"),
    path('ListDistrict/', views.ListDistrictsLocation, name="adminlistdistrictlocations"),

    path('ListVehicleType/', views.ListVehicleType, name="adminlistvehicletype"),
    path('AddVehicleType/', views.AddVehicleType, name="adminaddvehicletype"),
    path('EditVehicleTypes/<int:pk>', views.EditVehicleType, name="adminEditVehicleType"),
    path('UpdateVehicleTypes/', views.UpdateVehicleType, name="adminUpdateVehicleType"),
    path('DeleteVehicleTypes/<int:pk>', views.DeleteVehicleType, name="adminDeleteVehicleType"),

    path('EditProfile/', views.EditProfile, name="adminEditProfile"),
    path('UpdateProfile/', views.UpdateProfile, name="adminUpdateProfile"),
    path('UpdatePassword/', views.UpdatePassword, name="adminChangePassword"),

    path('ListRoutes/', views.ListRoutes, name="adminListRoute"),
    path('DeleteRoute/<int:pk>', views.DeleteRoute, name="adminDeleteRoute"),
    path('EditRoutes/<int:pk>', views.EditRoute, name="adminEditRoute"),
    path('UpdateRoutes/', views.UpdateRoute, name="adminUpdateRoute"),
    path('SetRoute/', views.SetRoute, name="adminSetRoute"),

    path('ListToll/', views.ListTollBooths, name="adminListToll"),
    path('SetToll/', views.AddTollBooths, name="adminSetToll"),
    path('EditToll/<int:pk>', views.EditTolls, name="adminEditToll"),
    path('UpdateToll/', views.UpdateTolls, name="adminUpdateToll"),
    path('DeleteToll/<int:pk>', views.DeleteTolls, name="adminDeleteToll"),

    path('ListCharge/', views.ListCharges, name="adminListCharge"),
    path('SetCharge/', views.SetCharges, name="adminSetCharge"),
    path('EditCharges/<int:pk>', views.EditCharge, name="adminEditCharge"),
    path('UpdateCharges/', views.UpdateCharge, name="adminUpdateCharge"),
    path('DeleteCharges/<int:pk>', views.DeleteCharge, name="adminDeleteCharge"),

    path('ListBooking/', views.BookingHistory, name="adminListBooking"),
]

Home/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
    url(r'^$', views.Index, name="Index"),
    url(r'^register/', views.Register, name="Register"),
    url(r'^tollregister/', views.TollRegister, name="TollRegister"),
    url(r'^login/', views.LoggingIn, name="Login"),
    url(r'^allauthRegistration/', views.allauthRegistration, name='allauthRegistration'),
    url(r'^Forget/', views.ForgetPassword, name='forget'),
    url(r'^NewPass/', views.NewPass, name='NewPass'),
    url(r'^ForgetPass/',views.NewPassword, name='forgetpassword'),
]

TollBooth/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from Home import views
from TollBooth import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('accounts/', include('allauth.urls')),
    path('admindash/', include('AdminDashboard.urls')),
    path('Workers/', include('WorkersDashboard.urls')),
    path('Customers/', include('CustomerDashboard.urls')),
    path('logout/', views.Logout, name="logout"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

AdminDashboard/models.py
from django.db import models

# Create your models here.


class AddDistrict(models.Model):
    DistrictName = models.CharField(max_length=256)
    isdeleted = models.BooleanField(default=False)


class AddLocations(models.Model):
    CityName = models.CharField(max_length=256)
    DistrictId = models.ForeignKey(AddDistrict, on_delete=models.CASCADE)
    isdeleted = models.BooleanField(default=False)


class AddRoute(models.Model):
    RouteName = models.CharField(max_length=256)
    SourceLoc = models.ForeignKey(AddLocations, on_delete=models.CASCADE, related_name='SourceLoc')
    DestinationLoc = models.ForeignKey(AddLocations, on_delete=models.CASCADE, related_name='DestinationLoc')
    isdeleted = models.BooleanField(default=False)


class AddToll(models.Model):
    TollName = models.CharField(max_length=256)
    RouteID = models.ForeignKey(AddRoute, on_delete=models.CASCADE)
    isdeleted = models.BooleanField(default=False)


class AddVehicle(models.Model):
    VehicleType = models.CharField(max_length=30)
    isdeleted = models.BooleanField(default=False)


class AddPriceCharge(models.Model):
    Amount = models.IntegerField()
    TollID = models.ForeignKey(AddToll, on_delete=models.CASCADE)
    VehicleTypeID = models.ForeignKey(AddVehicle, on_delete=models.CASCADE)
    isdeleted = models.BooleanField(default=False)

AdminDashboard/views.py
import datetime
from django.contrib.auth.hashers import make_password, check_password
from django.contrib import messages
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render

from AdminDashboard.models import *
from Home.models import *
from CustomerDashboard.models import *

# Create your views here.


def adminIndex(request):
    datime = datetime.date.today()
    noofusers = Login.objects.filter(roleid=3, isdeleted=False).count()
    noofworkers = Login.objects.filter(roleid=2, isdeleted=False, isapproved=True).count()
    noofbooths = AddToll.objects.filter(isdeleted=False).count()
    noofbooking = Booking.objects.filter(isCanceled=False, isExpired=False).count()
    context = {
        'datetime': datime,
        'noofusers': noofusers,
        'noofworkers': noofworkers,
        'noofbooths': noofbooths,
        'noofbooking': noofbooking,
    }
    return render(request, "AdminDashboard/adminindex.html", context)


def adminWorkersList(request):
    tolllog = TollRegisterAdditional.objects.filter(workerid__loginid__isdeleted=False, workerid__loginid__roleid=2).order_by('-pk')
    return render(request, "AdminDashboard/adminworkerslist.html", {'tolllog': tolllog})


def ApproveWorker(request, id):
    regobj = Registration.objects.get(pk=id)
    field_object = Registration._meta.get_field('loginid')
    field_value = field_object.value_from_object(regobj)
    log = Login.objects.get(pk=field_value)
    log.isapproved = True
    log.status = True
    log.save()
    messages.info(request, "Approved {}".format(log.username))
    return HttpResponseRedirect('/admindash/workerslist')


def RejectWorker(request, id):
    regobj = Registration.objects.get(pk=id)
    field_object = Registration._meta.get_field('loginid')
    field_value = field_object.value_from_object(regobj)
    log = Login.objects.get(pk=field_value)
    log.isapproved = False
    log.status = True
    log.save()
    messages.info(request, "Rejected {}".format(log.username))
    return HttpResponseRedirect('/admindash/workerslist')


def adminCustomerList(request):
    log = Registration.objects.select_related().filter(loginid__isdeleted=False).filter(loginid__roleid=3)
    vehdetails = VehicleReg.objects.filter(loginid__isdeleted=False, loginid__roleid=3, isdeleted=False)
    return render(request, "AdminDashboard/admincustomer.html", {'log':log, 'vehdetails': vehdetails})


def AddDistricts(request):
    if request.method == 'POST':
        districtname = request.POST.get('adddistrict')
        dist = AddDistrict()
        dist.DistrictName = districtname
        dist.isdeleted = False
        if AddDistrict.objects.filter(DistrictName=districtname).filter(isdeleted=False).exists():
            messages.warning(request, "Already Exist!")
            return HttpResponseRedirect('/admindash/ListDistrict')
        else:
            dist.save()
            messages.success(request, "Added Successfully")
            return HttpResponseRedirect('/admindash/ListDistrict')
    return render(request, "AdminDashboard/adminDistrictLocations.html")


def AddLocation(request):
    if request.method == 'POST':
        cityname = request.POST.get('addlocation')
        districtname = request.POST.get('district')
        did = AddDistrict.objects.get(DistrictName=districtname)
        loc = AddLocations()
        loc.CityName = cityname
        loc.DistrictId = did
        loc.isdeleted = False
        if AddLocations.objects.filter(CityName=cityname).filter(isdeleted=False).exists():
            messages.warning(request, "Already Exist!")
            return HttpResponseRedirect('/admindash/ListDistrict')
        else:
            loc.save()
            messages.success(request, "Added Successfully")
            return HttpResponseRedirect('/admindash/ListDistrict')
    return render(request, "AdminDashboard/adminDistrictLocations.html")


def EditDistrict(request, pk):
    dob = AddDistrict.objects.get(pk=pk)
    data = {
        'Id': dob.pk,
        'DistrictName': dob.DistrictName
    }
    return JsonResponse(data)


def UpdateDistrict(request):
    if request.POST.get('action') == 'post':
        id = request.POST.get('id')
        name = request.POST.get('DistrictName')
        dobj = AddDistrict.objects.get(pk=id)
        dobj.DistrictName = name
        if AddDistrict.objects.filter(DistrictName=name).filter(isdeleted=False).exists():
            message = {'error': "Already exists"}
            messages.warning(request, "Already Exist!")
            return JsonResponse(message)
        else:
            dobj.save()
            message = {'message': 'Success'}
            messages.success(request, "Updated Successfully")
            return JsonResponse(message)


def DeleteDistrict(request, pk):
    dob = AddDistrict.objects.get(pk=pk)
    dob.isdeleted = True
    if AddLocations.objects.filter(DistrictId=pk, isdeleted=False).exists():
        distdat = AddDistrict.objects.filter(isdeleted=False)
        locdat = AddLocations.objects.select_related().filter(isdeleted=False)
        context = {
            'nodelete': 'Can\'t Delete, Because {} is already in location'.format(dob.DistrictName),
            'distdat':distdat, 'locdata':locdat
        }
        return render(request, "AdminDashboard/adminDistrictLocations.html", context)
    else:
        dob.save()
        messages.error(request, "Deleted Successfully")
    return HttpResponseRedirect('/admindash/ListDistrict')


def EditLocation(request, pk):
    lob = AddLocations.objects.get(pk=pk)
    data = {
        'Id': lob.pk,
        'DistrictId': lob.DistrictId.DistrictName,
        'CityName': lob.CityName
    }
    return JsonResponse(data)


def UpdateLocation(request):
    if request.POST.get('action') == 'post':
        id = request.POST.get('id')
        dname = request.POST.get('DistrictId')
        lname = request.POST.get('CityName')
        dobj = AddDistrict.objects.get(DistrictName=dname)
        lobj = AddLocations.objects.get(pk=id)
        lobj.CityName = lname
        lobj.DistrictId = dobj
        if AddLocations.objects.filter(CityName=lname).filter(DistrictId=dobj.id).filter(isdeleted=False).exists():
            message = {'error': "Already exists"}
            messages.warning(request, "Already Exist!")
            return JsonResponse(message)
        else:
            lobj.save()
            message = {'message': 'Success'}
            messages.success(request, "Updated Successfully")
            return JsonResponse(message)


def DeleteLocation(request, pk):
    lob = AddLocations.objects.get(pk=pk)
    lob.isdeleted = True
    if AddRoute.objects.filter(SourceLoc=pk, isdeleted=False).exists() | AddRoute.objects.filter(DestinationLoc=pk, isdeleted=False).exists():
        distdat = AddDistrict.objects.filter(isdeleted=False)
        locdat = AddLocations.objects.select_related().filter(isdeleted=False)
        context = {
            'nolocation': 'Can\'t Delete, Because {} is already in route'.format(lob.CityName),
            'distdat':distdat, 'locdata':locdat
        }
        return render(request, "AdminDashboard/adminDistrictLocations.html", context)
    else:
        lob.save()
        messages.error(request, "Deleted Successfully")
        return HttpResponseRedirect('/admindash/ListDistrict')


def ListDistrictsLocation(request):
    distdat = AddDistrict.objects.filter(isdeleted=False)
    locdat = AddLocations.objects.select_related().filter(isdeleted=False)
    return render(request, "AdminDashboard/adminDistrictLocations.html", {'distdat':distdat, 'locdata':locdat})


def AddVehicleType(request):
    if request.method == "POST":
        vehtype = request.POST.get('vehtype')

        vehobj = AddVehicle()
        vehobj.VehicleType = vehtype
        vehobj.isdeleted = False
        if AddVehicle.objects.filter(VehicleType=vehtype, isdeleted=False).exists():
            messages.warning(request, "Already Exist!")
            return HttpResponseRedirect('/admindash/ListVehicleType')
        else:
            vehobj.save()
            messages.success(request, "Added Successfully")
            return HttpResponseRedirect('/admindash/ListVehicleType')
    return render(request, "AdminDashboard/adminAddVehType.html")


def EditVehicleType(request, pk):
    vob = AddVehicle.objects.get(pk=pk)
    data = {
        'Id': vob.pk,
        'VehicleType': vob.VehicleType,
    }
    return JsonResponse(data)


def UpdateVehicleType(request):
    if request.POST.get('action') == 'post':
        id = request.POST.get('id')
        vname = request.POST.get('VehicleType')
        vobj = AddVehicle.objects.get(pk=id)
        vobj.VehicleType = vname
        if AddVehicle.objects.filter(VehicleType=vname).filter(isdeleted=False).exists():
            message = {'error': "Already exists"}
            messages.warning(request, "Already Exist!")
            return JsonResponse(message)
        else:
            vobj.save()
            message = {'message': 'Success'}
            messages.success(request, "Updated Successfully")
            return JsonResponse(message)


def DeleteVehicleType(request, pk):
    vob = AddVehicle.objects.get(pk=pk)
    vob.isdeleted = True
    if AddPriceCharge.objects.filter(VehicleTypeID=pk, isdeleted=False).exists():
        vehicleobj = AddVehicle.objects.filter(isdeleted=False)
        context = {
            'novehicle': 'Can\'t Delete, Because there is an existing data for {}'.format(vob.VehicleType),
            'vehicleobj': vehicleobj
        }
        return render(request, "AdminDashboard/adminAddVehType.html", context)
    else:
        vob.save()
        messages.error(request, "Deleted Successfully")
        return HttpResponseRedirect('/admindash/ListVehicleType')


def ListVehicleType(request):
    vehicleobj = AddVehicle.objects.filter(isdeleted=False)
    return render(request, "AdminDashboard/adminAddVehType.html", {'vehicleobj': vehicleobj})

templates/AdminDashboard/adminBookingHistory.html
{% extends 'AdminDashboard/adminbase.html' %}
{% block body_block %}
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'AdminDashboard:adminindex' %}">Dashboard</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Booking</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Booking History</h4>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead >
                                            <tr>
                                                <th>#</th>
                                                <th>First Name</th>
                                                <th>Mobile</th>
                                                <th>Email</th>
                                                <th>Register No</th>
                                                <th>TollBooth</th>
                                                <th>Source Location</th>
                                                <th>Destination Location</th>
                                                <th>Amount</th>
                                                <th>Booked On</th>
                                                <th>Expired On</th>
                                                <th>Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for i in bookobjs %}
                                            <tr>
                                            <td>{{ forloop.counter }}</td>
                                            {% for j in newuserobjs %}
                                            {% if i.loginid == j.loginid %}
                                            <td>{{ j.FirstName }}</td>
                                            <td>{{j.Phone }}</td>
                                            <td>{{ j.Email }}</td>
                                            {% endif %}
                                            {% endfor %}
                                            <td>{{ i.VehicleID.VehicleRegNum }}</td>
                                            <td>{{ i.TollID.TollName }}</td>
                                            <td>{{ i.TollID.RouteID.SourceLoc.CityName }}</td>
                                            <td>{{ i.TollID.RouteID.DestinationLoc.CityName }}</td>
                                            <td>{{ i.AmountID.Amount }}</td>
                                            <td>{{ i.DateBooked }} {{ i.TimeBooked }}</td>
                                            <td>{{ i.DateExpired }} {{ i.TimeExpired }}</td>
                                                {% if i.isExpired == True and i.isCanceled == False and i.VehicleID.isdeleted == False %}
                                                    <td class="text-danger" style="font-weight: bold;">Expired</td>
                                                {% elif i.isExpired == False and i.isCanceled == False and i.VehicleID.isdeleted == False %}
                                                    <td class="text-info" style="font-weight: bold;">Active</td>
                                                {% elif i.isCanceled == True and i.isExpired == True and i.VehicleID.isdeleted == False %}
                                                    <td class="text-danger" style="font-weight: bold;">Canceled</td>
                                                {% elif i.isCanceled == True and i.isExpired == True and i.VehicleID.isdeleted == True %}
                                                    <td class="text-danger" style="font-weight: bold;">Vehicle Deleted</td>
                                                {% endif %}
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
{% endblock %}

templates/AdminDashboard/adminbase.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Welcome | {{ logindetails.username }}</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'admin/images/favicon.png' %}">
    <!-- Pignose Calender -->
    <link href="{% static 'admin/plugins/pg-calendar/css/pignose.calendar.min.css' %}" rel="stylesheet">
    <!-- Chartist -->
    <link rel="stylesheet" href="{% static 'admin/plugins/chartist/css/chartist.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin/plugins/chartist-plugin-tooltips/css/chartist-plugin-tooltip.css' %}">
    <link href="{% static 'admin/plugins/tables/css/datatable/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/9e9d15e133.js" crossorigin="anonymous"></script>
    <!-- Custom Stylesheet -->
    <link href="{% static 'admin/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'admin/icons/fontawesome-free-5.12.1-web/css/all.min.css' %}" rel="stylesheet">

</head>

<body>

    <!--*******************
        Preloader start
    ********************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header">
            <div class="brand-logo">
                <a href="{% url 'AdminDashboard:adminindex' %}">
                    <b class="logo-abbr"><span style="font-size: 25px; color: white; font-weight: bold">TB</span> </b>
                    <span class="logo-compact" style="font-weight: bold; color: white; font-size: 30px;">TBOOTH</span>
                    <span class="brand-title" style="font-weight: bold; color: white; font-size: 30px;">
                        TBOOTH
                    </span>
                </a>
            </div>
        </div>
        <!--**********************************
            Nav header end
        ***********************************-->

        <!--**********************************
            Header start
        ***********************************-->

        <div class="header">
            <div class="header-content clearfix">

                <div class="nav-control">
                    <div class="hamburger">
                        <span class="toggle-icon"><i class="icon-menu"></i></span>
                    </div>

                </div>
                <div class="header-left">
                    <div class="input-group icons">
                        <h2 style="color:rgba(14,13,12,0.93)">Welcome, {{ logindetails.username }}</h2>
                    </div>
                </div>
                <div class="header-right">
                    <ul class="clearfix">
                        <li class="icons dropdown">
                            <div class="user-img c-pointer position-relative"   data-toggle="dropdown">
                                <span class="activity active"></span>
                                <img src="{{ userdetails.Image.url }}" height="40" width="40" alt="">
                            </div>
                            <div class="drop-down dropdown-profile animated fadeIn dropdown-menu">
                                <div class="dropdown-content-body">
                                    <ul>
                                        <li>
                                            <a href="{% url 'AdminDashboard:adminEditProfile' %}"><i class="fas fa-user-secret"></i> <span>Profile</span></a>
                                        </li>

                                        <hr class="my-2">
                                        <li><a href="{% url 'logout' %}"><i class="fas fa-power-off"></i> <span>Logout</span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            {% include 'AdminDashboard/messages.html' %}
        </div>
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->

        <!--**********************************
            Sidebar start
        ***********************************-->
        <div class="nk-sidebar">
            <div class="nk-nav-scroll">
                <ul class="metismenu" id="menu">
                    <li class="nav-label">Dashboard</li>
                    <li>
                        <a href="{% url 'AdminDashboard:adminindex' %}" aria-expanded="false">
                            <i class="fab fa-dashcube menu-icon"></i><span class="nav-text">Dashboard</span>
                        </a>
                    </li>
                    <li class="mega-menu mega-menu-sm">
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="fas fa-users menu-icon"></i><span class="nav-text">Registered Users</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'AdminDashboard:adminworkerslist' %}">Workers</a></li>
                            <li><a href="{% url 'AdminDashboard:admincustomerslist' %}">Users</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="{% url 'AdminDashboard:adminlistdistrictlocations' %}" aria-expanded="false">
                            <i class="fas fa-location-arrow menu-icon"></i><span class="nav-text">District/Locations</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'AdminDashboard:adminListRoute' %}" aria-expanded="false">
                            <i class="fas fa-road menu-icon"></i><span class="nav-text">Add Route</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'AdminDashboard:adminListToll' %}" aria-expanded="false">
                            <i class="fas fa-torii-gate menu-icon"></i><span class="nav-text">Add TollBooth</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'AdminDashboard:adminlistvehicletype' %}" aria-expanded="false">
                            <i class="fas fa-car menu-icon"></i><span class="nav-text">Add Vehicle Type</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'AdminDashboard:adminListCharge' %}" aria-expanded="false">
                            <i class="fas fa-rupee-sign menu-icon"></i><span class="nav-text">Set Price Charge</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'AdminDashboard:adminListBooking' %}" aria-expanded="false">
                            <i class="fas fa-history menu-icon"></i><span class="nav-text">Booking History</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        {% block body_block %}


        {% endblock %}
        <div class="footer">
            <div class="copyright">
                <p>Copyright &copy; Designed & Developed by dN</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->
    </div>
    <!--*******************
        Preloader end
    ********************-->


    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->

    <!--**********************************
        Scripts
    ***********************************-->
    <script src="{% static 'admin/plugins/common/common.min.js' %}"></script>
    <script src="{% static 'admin/js/custom.min.js' %}"></script>
    <script src="{% static 'admin/js/settings.js' %}"></script>
    <script src="{% static 'admin/js/gleek.js' %}"></script>
    <script src="{% static 'admin/js/styleSwitcher.js' %}"></script>

    <!-- Chartjs -->
    <script src="{% static 'admin/plugins/chart.js/Chart.bundle.min.js' %}"></script>
    <!-- Circle progress -->
    <script src="{% static 'admin/plugins/circle-progress/circle-progress.min.js' %}"></script>
    <!-- Datamap -->
    <script src="{% static 'admin/plugins/d3v3/index.js' %}"></script>
    <script src="{% static 'admin/plugins/topojson/topojson.min.js' %}"></script>
    <script src="{% static 'admin/plugins/datamaps/datamaps.world.min.js' %}"></script>
    <!-- Morrisjs -->
    <script src="{% static 'admin/plugins/raphael/raphael.min.js' %}"></script>
    <script src="{% static 'admin/plugins/morris/morris.min.js' %}"></script>
    <!-- Pignose Calender -->
    <script src="{% static 'admin/plugins/moment/moment.min.js' %}"></script>
    <script src="{% static 'admin/plugins/pg-calendar/js/pignose.calendar.min.js' %}"></script>
    <!-- ChartistJS -->
    <script src="{% static 'admin/plugins/chartist/js/chartist.min.js' %}"></script>
    <script src="{% static 'admin/plugins/chartist-plugin-tooltips/js/chartist-plugin-tooltip.min.js' %}"></script>
    <script src="{% static 'admin/plugins/tables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'admin/plugins/tables/js/datatable/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'admin/plugins/tables/js/datatable-init/datatable-basic.min.js' %}"></script>


    <script src="{% static 'admin/js/dashboard/dashboard-1.js' %}"></script>

    <script>
        setTimeout(function () {
        if($("#msg").length > 0) {
            $("#msg").remove();
        }
        }, 4000)
    </script>
</body>
</html>

templates/AdminDashboard/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}